
name: 'cce-slack-notification-action'
author: 'CleanChoice Energy'
description: 'Composite action for Slack notification'
inputs:
  channel:
    description: 'Name or ID of the Slack channel'
    required: true
  status:
    description: 'Custom status as a string'
    required: true
  color:
    description: 'Slack color line'
    required: true
  message_id:
    description: 'Update prev message'
    required: false
outputs:
  message_id:
    description: "ID of message"
    value: ${{ steps.slack.outputs.ts }}
runs:
  using: 'composite'
  steps:
    - name: Convert Slack channel ID to Name
      shell: bash
      run: |
        get_channel_id=$(curl -X GET "https://slack.com/api/conversations.list?limit=1000&pretty=1" \
        -H  "accept: application/x-www-form-urlencoded" \
        -H  "Authorization: Bearer ${{ env.SLACK_BOT_TOKEN }}" | jq -r '.channels[]|select(.name=="'${{ inputs.channel }}'") | .id')
        echo "channel_id=$get_channel_id" >> $GITHUB_ENV
    - name: Set Slack color
      shell: bash
      run: |
        if [[ ${{ inputs.color }} == 'warning' ]]; then
          echo "emoji=:hourglass_flowing_sand:" >> $GITHUB_ENV
        elif [[ ${{ inputs.color }} == 'good' ]]; then
          echo "emoji=:white_check_mark:" >> $GITHUB_ENV
        elif [[ ${{ inputs.color }} == 'danger' ]]; then
          echo "emoji=:red_circle:" >> $GITHUB_ENV
        fi
    - name: Set Statuses
      shell: bash
      id: status
      run: |
        for each in $(echo ${{ inputs.status }})
        do
          echo $each
          echo "${{ env.emoji }} $each" >> slack_statuses
        done
        test_string=$(cat << EOF
        $(cat slack_statuses)
        EOF
        )
        cat slack_statuses
        statuses="${test_string//$'\n'/'%0A'}"
        echo "statuses=$statuses" >> $GITHUB_OUTPUT
        rm -f ./slack_statuses
    - name: Set Timestamp
      shell: bash
      run: echo "timestamp=$(date +%s)" >> $GITHUB_ENV
    - name: Slack Action
      uses: slackapi/slack-github-action@v1
      id: slack
      with:
        channel-id: "${{ env.channel_id }}" 
        update-ts: ${{ inputs.message_id }}
        payload: |
          {
            "text": ":github: Workflow run by: *${{ github.actor }}*",
            "attachments": [
              {
                "color": "${{ inputs.color }}",
                "fields": [
                  {
                    "title": "Repo",
                    "short": true,
                    "value": "<https://github.com/${{ github.repository }}|${{ github.repository }}>"
                  },
                  {
                    "title": "Workflow",
                    "short": true,
                    "value": "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>"
                  },
                  {
                    "title": "Status",
                    "value": "${{ steps.status.output.statuses}}",
                    "short": true
                  },
                  {
                    "title": "Branch",
                    "value": "<https://github.com/${{ github.repository }}/tree/${{ github.head_ref || github.ref_name}}|${{ github.head_ref || github.ref_name}}>",
                    "short": true
                  },
                  {
                    "title": "Event",
                    "value": "<${{ github.event.pull_request.html_url || github.event.head_commit.url }}|${{ github.event_name }}>",
                    "short": true
                  }
                ],
                "footer": "${{ github.repository }}",
                "footer_icon": "https://scontent-arn2-2.xx.fbcdn.net/v/t1.6435-9/69063507_3531984646874690_7772827298843066368_n.png?_nc_cat=100&ccb=1-7&_nc_sid=174925&_nc_ohc=j4iC0WAS7xgAX9dPpIu&_nc_ht=scontent-arn2-2.xx&oh=00_AfBviMf2oRH1PbHc9zspigJu0mhg9zBbbijDX-ra3MtGZA&oe=63B113D2",
                "ts": "${{ env.timestamp }}"
              }
            ]
          }